### ISSUE TITLE
ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None

### ISSUE THREAD

**Issue by riya-maan** [klauscc/lipnet-replication#5]
I am trying to train the system in Python 2.7 environment. I'm getting following error:

> Epoch 1/500
> steps per epoch : 89
> Process Process-1:
> Traceback (most recent call last):
>   File "/Users/riyamaan/anaconda3/envs/python2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
>     self.run()
>   File "/Users/riyamaan/anaconda3/envs/python2/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/riyamaan/anaconda3/envs/python2/lib/python2.7/site-packages/keras/engine/training.py", line 606, in data_generator_task
>     generator_output = next(self._generator)
>   File "/Users/riyamaan/Desktop/lipnet-replication/gridDatasetGenerator.py", line 49, in next_train_batch
>     yield self.imageSequenceGenerator.flow(super(GRIDDatasetGenerator, self).next_train_batch(batch_size, gen_words=gen_words))
>   File "/Users/riyamaan/Desktop/lipnet-replication/preprocessing/image_sequence.py", line 59, in flow
> Process Process-2:
> Traceback (most recent call last):
>   File "/Users/riyamaan/anaconda3/envs/python2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
>     inputs,outputs = next(generator)
>   File "/Users/riyamaan/Desktop/lipnet-replication/gridBaseDataset.py", line 42, in next_train_batch
>     yield self.gen_batch(start_pos, batch_size, self.train_paths, gen_words=gen_words)
>   File "/Users/riyamaan/Desktop/lipnet-replication/gridBaseDataset.py", line 68, in gen_batch
>     lip_d, lip_l, lip_label_len, source_str = self.readLipSequences(paths[pos], gen_words=gen_words)
>   File "/Users/riyamaan/Desktop/lipnet-replication/gridBaseDataset.py", line 217, in readLipSequences
>     read_images(frames[i])
>   File "/Users/riyamaan/Desktop/lipnet-replication/gridBaseDataset.py", line 210, in read_images
>     lip_sequence[i-begin_frame,...] = self.load_image(img_name, target_size=self.target_size)
>   File "/Users/riyamaan/Desktop/lipnet-replication/gridBaseDataset.py", line 175, in load_image
>     self.run()
>     img = pil_image.open(path)
>   File "/Users/riyamaan/anaconda3/envs/python2/lib/python2.7/site-packages/PIL/Image.py", line 2609, in open
>   File "/Users/riyamaan/anaconda3/envs/python2/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/riyamaan/anaconda3/envs/python2/lib/python2.7/site-packages/keras/engine/training.py", line 606, in data_generator_task
>     generator_output = next(self._generator)
>   File "/Users/riyamaan/Desktop/lipnet-replication/gridDatasetGenerator.py", line 49, in next_train_batch
>     yield self.imageSequenceGenerator.flow(super(GRIDDatasetGenerator, self).next_train_batch(batch_size, gen_words=gen_words))
>   File "/Users/riyamaan/Desktop/lipnet-replication/preprocessing/image_sequence.py", line 59, in flow
>     inputs,outputs = next(generator)
>   File "/Users/riyamaan/Desktop/lipnet-replication/gridBaseDataset.py", line 42, in next_train_batch
> Traceback (most recent call last):
>   File "train_multiuser.py", line 40, in <module>
>     callbacks=[statisticCallback, statisticCallback_unseen]
>   File "/Users/riyamaan/anaconda3/envs/python2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
>     return func(*args, **kwargs)
>   File "/Users/riyamaan/anaconda3/envs/python2/lib/python2.7/site-packages/keras/engine/training.py", line 1852, in fit_generator
>     str(generator_output))
> ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None

@klauscc can you please help me to resolve it!

**Comment by riya-maan** [comment]
Used Keras==2.1.2. Works fine now
